deployments:
  k8s:
    kubernetes_manifest: ./pods/storage/redis.yaml
    deployment_type: kubernetes
    kubernetes_default_pod: redis
    use_kubernetes_registry: true
    port_forwarding: 6379:6379
    check_service_ports: 6379
    copy_files_build_process: /assets/smth ~/code/local
