apiVersion: v1
kind: Pod
metadata:
  name: redis
spec:
  containers:
  - name: redis
    image: redis
    ports:
    - containerPort: 6379
      name: redis-db
    volumeMounts:
    - name: redis-storage
      mountPath: /data/redis
    volumeMounts:
    - name: redis-storage-local
      mountPath: /data/local
  volumes:
  - name: redis-storage
    hostPath:
      path: /assets/data
      type: Directory
  - name: redis-storage-local
    hostPath:
      path: ~/code/local
      type: Directory
