apiVersion: v1
kind: Pod
metadata:
  name: redis
spec:
  containers:
  - name: redis
    image: redis
    ports:
    - port: 6379
      targetPort: 6379
      name: redis-db
    volumeMounts:
    - name: redis-storage
      mountPath: /assets/redis
  volumes:
  - name: redis-storage
    emptyDir: {}
